// ==========================================================================
// 🌿 CRM CLÍNICO FARMACÊUTICO — BASE CANÔNICA DE MEDICAMENTOS & FARMACOLOGIA (ANVISA / DCB)
// Catálogo farmacoterapêutico de referência com Mapeamento de Laboratórios / Fabricantes
// ==========================================================================

export const CANONICAL_MEDICATIONS_DB = [
  // ─── ANALGÉSICOS, ANTITÉRMICOS & ANTI-INFLAMATÓRIOS ───────────────────────
  {
    id: 'MED-CAN-001',
    name: 'Dipirona Monoidratada',
    activeSubstance: 'Dipirona Monoidratada (Metamizol)',
    tradeNames: ['Novalgina', 'Anador', 'Lisador', 'Doralgina', 'Maxiliv'],
    manufacturer: 'Sanofi-Aventis',
    laboratories: ['Sanofi-Aventis', 'EMS', 'Medley', 'Eurofarma', 'Neo Química', 'Cimed', 'Teuto', 'Prati-Donaduzzi'],
    atcCode: 'ATC_N02BB02',
    pharmaceuticalClass: 'Analgésico e Antitérmico Derivado das Pirazolonas',
    therapeuticClass: 'Analgésicos e Antitérmicos',
    pharmaceuticalForms: ['Comprimido 500mg', 'Comprimido 1g', 'Solução Oral Gotas 500mg/ml', 'Ampola Injetável 500mg/ml'],
    usualDosages: ['500mg', '1g', '500mg/ml'],
    defaultPosology: '1 comprimido de 500mg a 1g a cada 6 horas se dor ou febre (máx 4g/dia)',
    indications: ['Dor aguda de intensidade leve a moderada', 'Febre refratária', 'Cefaleia', 'Dor pós-operatória'],
    contraindications: ['Hipersensibilidade a pirazolonas', 'Porfiria hepática aguda', 'Deficiência congênita de G6PD', 'Gravidez no 3º trimestre'],
    symptomKeywords: ['dor', 'febre', 'dor de cabeca', 'cefaleia', 'mialgia', 'dor no corpo', 'gripe', 'moleza', 'enxaqueca'],
    pregnancyCategory: 'C',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-002',
    name: 'Paracetamol',
    activeSubstance: 'Paracetamol (Acetaminofeno)',
    tradeNames: ['Tylenol', 'Dôrico', 'Parador', 'Cimegripe', 'Resfenol'],
    manufacturer: 'Johnson & Johnson (Kenvue)',
    laboratories: ['Johnson & Johnson', 'EMS', 'Medley', 'Eurofarma', 'Neo Química', 'Cimed', 'Aché', 'Teuto'],
    atcCode: 'ATC_N02BE01',
    pharmaceuticalClass: 'Analgésico e Antitérmico Derivado do Para-aminofenol',
    therapeuticClass: 'Analgésicos e Antitérmicos',
    pharmaceuticalForms: ['Comprimido 500mg', 'Comprimido 750mg', 'Suspensão Gotas 200mg/ml', 'Xarope 32mg/ml'],
    usualDosages: ['500mg', '750mg', '200mg/ml'],
    defaultPosology: '1 comprimido de 500mg a 750mg de 6/6h ou 8/8h (dose máxima 3g a 4g/dia)',
    indications: ['Alívio de dores leves a moderadas', 'Redução da febre em adultos e crianças', 'Opção de 1ª linha em gestantes e dengue'],
    contraindications: ['Hepatopatia grave / Insuficiência hepática', 'Uso concomitante e abusivo com bebidas alcoólicas'],
    symptomKeywords: ['dor', 'febre', 'dor leve', 'gripe', 'resfriado', 'dengue', 'gestante dor', 'dor dente', 'febre infantil'],
    pregnancyCategory: 'B',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-003',
    name: 'Ibuprofeno',
    activeSubstance: 'Ibuprofeno',
    tradeNames: ['Advil', 'Alivium', 'Ibupril', 'Spidufen', 'Motrin'],
    manufacturer: 'Haleon / Aché',
    laboratories: ['Haleon', 'Aché', 'EMS', 'Medley', 'Eurofarma', 'Neo Química', 'Cimed', 'Zambon'],
    atcCode: 'ATC_M01AE01',
    pharmaceuticalClass: 'Anti-inflamatório Não Esteroidal (AINE) Derivado do Ácido Propiônico',
    therapeuticClass: 'Anti-inflamatórios e Antirreumáticos',
    pharmaceuticalForms: ['Cápsula Líquida 400mg', 'Comprimido 600mg', 'Suspensão Gotas 50mg/ml', 'Suspensão Gotas 100mg/ml'],
    usualDosages: ['200mg', '400mg', '600mg', '100mg/ml'],
    defaultPosology: '1 comprimido de 400mg a 600mg de 8/8h após as refeições (por até 5 dias)',
    indications: ['Processos inflamatórios agudos', 'Dor muscular e articular', 'Dismenorreia primária (cólica menstrual)', 'Odontalgia'],
    contraindications: ['Úlcera péptica ativa', 'Insuficiência renal ou cardíaca grave', 'Hipertensão descompensada', 'Uso concomitante com Varfarina/Anticoagulantes'],
    symptomKeywords: ['inflamacao', 'dor muscular', 'colica menstrual', 'dor dente', 'garganta inflamada', 'lombalgia', 'dor nas costas', 'artrite', 'torcicolo'],
    pregnancyCategory: 'C (D no 3º trimestre)',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-004',
    name: 'Cetoprofeno',
    activeSubstance: 'Cetoprofeno',
    tradeNames: ['Profenid', 'Bi-Profenid', 'Artrosil', 'Flamador'],
    manufacturer: 'Sanofi-Aventis',
    laboratories: ['Sanofi-Aventis', 'EMS', 'Medley', 'Eurofarma', 'Neo Química', 'Aché', 'Cimed'],
    atcCode: 'ATC_M01AE03',
    pharmaceuticalClass: 'Anti-inflamatório Não Esteroidal (AINE)',
    therapeuticClass: 'Anti-inflamatórios e Antirreumáticos',
    pharmaceuticalForms: ['Comprimido 100mg', 'Comprimido 150mg Bi-Profenid', 'Cápsula 50mg', 'Gel Tópico 2.5%'],
    usualDosages: ['50mg', '100mg', '150mg'],
    defaultPosology: '1 comprimido de 150mg 1 vez ao dia (ou 100mg de 12/12h) após refeição',
    indications: ['Inflamações musculoesqueléticas intensas', 'Tendinites', 'Bursites', 'Lombociatalgia'],
    contraindications: ['Histórico de hemorragia digestiva', 'Asma induzida por AINEs', 'Insuficiência renal grave'],
    symptomKeywords: ['dor forte costas', 'tendinite', 'bursite', 'nervo ciatico', 'inflamacao forte', 'dor no joelho'],
    pregnancyCategory: 'D',
    prescriptionType: 'Sob Prescrição'
  },
  {
    id: 'MED-CAN-005',
    name: 'Dipirona + Orfenadrina + Cafeína',
    activeSubstance: 'Dipirona Monoidratada + Citrato de Orfenadrina + Cafeína Anidra',
    tradeNames: ['Dorflex', 'Doricin', 'Nevralgex', 'Miorrelax', 'Sedalex'],
    manufacturer: 'Sanofi-Aventis',
    laboratories: ['Sanofi-Aventis', 'EMS', 'Neo Química', 'Cimed', 'Eurofarma', 'Medley'],
    atcCode: 'ATC_M03BC51',
    pharmaceuticalClass: 'Analgésico Combinado com Relaxante Muscular de Ação Central',
    therapeuticClass: 'Relaxantes Musculares e Analgésicos',
    pharmaceuticalForms: ['Comprimido', 'Solução Oral Gotas'],
    usualDosages: ['Comprimido padrão', 'Gotas'],
    defaultPosology: '1 a 2 comprimidos de 8/8h ou 6/6h conforme a dor muscular (máx 6 comp/dia)',
    indications: ['Contratura muscular dolorosa', 'Torcicolo', 'Cefaleia tensional associada a tensão cervical'],
    contraindications: ['Glaucoma de ângulo estreito', 'Miastenia gravis', 'Alergia a dipirona'],
    symptomKeywords: ['dor muscular', 'torcicolo', 'musculo travado', 'pescoco travado', 'dorflex', 'tensao muscular', 'contratura'],
    pregnancyCategory: 'C',
    prescriptionType: 'MIP'
  },

  // ─── RESPIRATÓRIOS & ANTI-HISTAMÍNICOS ────────────────────────────────────
  {
    id: 'MED-CAN-016',
    name: 'Loratadina',
    activeSubstance: 'Loratadina',
    tradeNames: ['Claritin', 'Loralerg', 'Histadin', 'Claratine'],
    manufacturer: 'Bayer',
    laboratories: ['Bayer', 'EMS', 'Medley', 'Eurofarma', 'Neo Química', 'Cimed', 'Aché', 'Teuto'],
    atcCode: 'ATC_R06AX13',
    pharmaceuticalClass: 'Anti-histamínico H1 de 2ª Geração (Não Sedante)',
    therapeuticClass: 'Antialérgicos e Anti-histamínicos',
    pharmaceuticalForms: ['Comprimido 10mg', 'Xarope 1mg/ml'],
    usualDosages: ['10mg', '1mg/ml'],
    defaultPosology: '1 comprimido de 10mg 1 vez ao dia (ou 10ml de xarope para crianças > 30kg)',
    indications: ['Rinite alérgica sazonal e perene', 'Coriza e espirros', 'Urticária e prurido alérgico'],
    contraindications: ['Hipersensibilidade à loratadina', 'Insuficiência hepática grave (ajustar dose em dias alternados)'],
    symptomKeywords: ['rinite', 'espirros', 'coriza', 'alergia', 'coceira no nariz', 'claritin', 'urticaria', 'olhos lacrimejando'],
    pregnancyCategory: 'B',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-017',
    name: 'Desloratadina',
    activeSubstance: 'Desloratadina',
    tradeNames: ['Desalex', 'Sigmaliv', 'Destadin', 'Eslotina'],
    manufacturer: 'Organon / Eurofarma',
    laboratories: ['Organon', 'Eurofarma', 'EMS', 'Medley', 'Aché', 'Neo Química', 'Cimed'],
    atcCode: 'ATC_R06AX27',
    pharmaceuticalClass: 'Anti-histamínico H1 de Última Geração (Metabólito Ativo)',
    therapeuticClass: 'Antialérgicos e Anti-histamínicos',
    pharmaceuticalForms: ['Comprimido Revestido 5mg', 'Xarope 0.5mg/ml'],
    usualDosages: ['5mg', '0.5mg/ml'],
    defaultPosology: '1 comprimido de 5mg via oral 1 vez ao dia (independente das refeições)',
    indications: ['Rinite alérgica crônica e aguda', 'Congestão nasal alérgica', 'Urticária idiopática crônica'],
    contraindications: ['Hipersensibilidade à desloratadina ou loratadina', 'Gravidez e lactação sem orientação'],
    symptomKeywords: ['desloratadina', 'desalex', 'rinite forte', 'alergia sem sono', 'coceira na pele', 'congestao alergica'],
    pregnancyCategory: 'B',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-018',
    name: 'Acetilcisteína',
    activeSubstance: 'N-Acetilcisteína',
    tradeNames: ['Fluimucil', 'Cisteil', 'Flucistein', 'Airela'],
    manufacturer: 'Zambon',
    laboratories: ['Zambon', 'EMS', 'Eurofarma', 'Medley', 'Aché', 'Neo Química', 'Cimed'],
    atcCode: 'ATC_R05CB01',
    pharmaceuticalClass: 'Mucolítico e Fluidificante das Secreções Brônquicas',
    therapeuticClass: 'Expectorantes e Mucolíticos',
    pharmaceuticalForms: ['Sachê Granulado 200mg', 'Sachê Granulado 600mg', 'Xarope 20mg/ml', 'Xarope 40mg/ml'],
    usualDosages: ['200mg', '600mg', '40mg/ml'],
    defaultPosology: '1 sachê de 600mg dissolvido em meio copo de água 1 vez ao dia (de preferência à noite)',
    indications: ['Tosse produtiva com catarro espesso', 'Bronquite aguda e crônica', 'Sinusite com acúmulo de secreção'],
    contraindications: ['Hipersensibilidade a acetilcisteína', 'Úlcera gastroduodenal ativa (cautela)', 'Crianças < 2 anos'],
    symptomKeywords: ['tosse com catarro', 'catarro preso', 'fluimucil', 'peito cheio', 'secrecao', 'expectorante', 'tosse produtiva'],
    pregnancyCategory: 'B',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-019',
    name: 'Cloreto de Sódio 0,9% (Solução Nasal)',
    activeSubstance: 'Cloreto de Sódio 0,9% Isotônico Estéril',
    tradeNames: ['Sorine', 'Rinosoro', 'Maresis', 'Salsep', 'Snif'],
    manufacturer: 'Aché / Hypera Pharma',
    laboratories: ['Aché', 'Hypera Pharma', 'Eurofarma', 'EMS', 'Cimed', 'Biolab'],
    atcCode: 'ATC_R01AX',
    pharmaceuticalClass: 'Fluidificante e Descongestionante Fisiológico Mecânico',
    therapeuticClass: 'Higienizadores e Descongestionantes Nasais Fisiológicos',
    pharmaceuticalForms: ['Spray Nasal 50ml / 100ml', 'Solução Gotas 30ml', 'Jato Contínuo'],
    usualDosages: ['0.9% spray ou gotas'],
    defaultPosology: '1 a 2 aplicações em cada narina várias vezes ao dia conforme necessidade',
    indications: ['Lavagem e desobstrução nasal', 'Hidratação da mucosa em tempo seco', 'Coadjuvante em gripes, sinusites e rinites'],
    contraindications: ['Nenhuma contraindicação conhecida para solução isotônica fisiológica'],
    symptomKeywords: ['nariz entupido', 'lavagem nasal', 'soro nasal', 'rinosoro', 'maresis', 'tempo seco', 'coriza'],
    pregnancyCategory: 'A',
    prescriptionType: 'MIP'
  },

  // ─── GASTROINTESTINAIS & CÓLICAS ─────────────────────────────────────────
  {
    id: 'MED-CAN-020',
    name: 'Butilbrometo de Escopolamina + Dipirona',
    activeSubstance: 'Butilbrometo de Escopolamina 10mg + Dipirona Monoidratada 250mg',
    tradeNames: ['Buscopan Composto', 'Butilmax Composto', 'Dorilax Cólica', 'Atroveran Composto'],
    manufacturer: 'Boehringer Ingelheim / Sanofi',
    laboratories: ['Boehringer Ingelheim', 'Sanofi', 'EMS', 'Eurofarma', 'Neo Química', 'Cimed', 'Hypera Pharma'],
    atcCode: 'ATC_A03DB04',
    pharmaceuticalClass: 'Antiespasmódico com Ação Analgésica Sinergética',
    therapeuticClass: 'Antiespasmódicos e Analgésicos Digestivos/Ginecológicos',
    pharmaceuticalForms: ['Drágea', 'Solução Oral Gotas 20ml', 'Ampola Injetável'],
    usualDosages: ['1 a 2 drágeas', '20 a 40 gotas'],
    defaultPosology: '1 a 2 drágeas de 8/8h ou 6/6h com um copo de água (máx 6 drágeas/dia)',
    indications: ['Cólicas intestinais e abdominais intensas', 'Cólicas menstruais (dismenorreia)', 'Espasmos das vias biliares e urinárias'],
    contraindications: ['Glaucoma de ângulo fechado', 'Miastenia gravis', 'Megacólon', 'Alergia a dipirona ou pirazolonas'],
    symptomKeywords: ['colica intestinal', 'dor na barriga', 'colica menstrual forte', 'buscopan', 'espasmo abdominal', 'dor no estomago com colica'],
    pregnancyCategory: 'C',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-011',
    name: 'Omeprazol',
    activeSubstance: 'Omeprazol Magnésico',
    tradeNames: ['Losec', 'Peprazol', 'Gastrium', 'Victrix', 'Omeprasec'],
    manufacturer: 'AstraZeneca / Aché',
    laboratories: ['AstraZeneca', 'Aché', 'EMS', 'Medley', 'Eurofarma', 'Neo Química', 'Cimed', 'Teuto'],
    atcCode: 'ATC_A02BC01',
    pharmaceuticalClass: 'Inibidor da Bomba de Prótons H+/K+ ATPase (IBP)',
    therapeuticClass: 'Antiácidos e Protetores Gástricos',
    pharmaceuticalForms: ['Cápsula 20mg', 'Cápsula 40mg', 'Frasco-Ampola Injetável 40mg'],
    usualDosages: ['20mg', '40mg'],
    defaultPosology: '20mg a 40mg pela manhã em jejum, 30 minutos antes do café da manhã',
    indications: ['Doença do Refluxo Gastroesofágico (DRGE)', 'Úlcera gástrica e duodenal', 'Erradicação de H. pylori', 'Proteção gástrica em uso de AINEs'],
    contraindications: ['Hipersensibilidade a IBPs', 'Atenção ao uso concomitante com Clopidogrel (redução da ativação)'],
    symptomKeywords: ['azia', 'queimacao', 'refluxo', 'dor no estomago', 'gastrite', 'protetor gastrico', 'empachamento'],
    pregnancyCategory: 'C',
    prescriptionType: 'MIP / Sob Prescrição'
  },
  {
    id: 'MED-CAN-012',
    name: 'Hidróxido de Alumínio + Hidróxido de Magnésio + Simeticona',
    activeSubstance: 'Hidróxido de Alumínio + Hidróxido de Magnésio + Simeticona',
    tradeNames: ['Mylanta Plus', 'Gastrobisa', 'Alumag', 'Gelmax', 'Estomazil'],
    manufacturer: 'Johnson & Johnson / Hypera Pharma',
    laboratories: ['Johnson & Johnson', 'Hypera Pharma', 'EMS', 'Eurofarma', 'Cimed', 'Neo Química'],
    atcCode: 'ATC_A02AF02',
    pharmaceuticalClass: 'Antiácido Neutralizante Combinado com Antiflatulento',
    therapeuticClass: 'Antiácidos e Antiflatulentos',
    pharmaceuticalForms: ['Suspensão Oral Frasco 240ml', 'Comprimidos Mastigáveis'],
    usualDosages: ['10ml a 20ml', '1 a 2 comprimidos'],
    defaultPosology: '10ml a 20ml (ou 1-2 comp mastigáveis) 1 hora após as refeições e ao deitar',
    indications: ['Alívio imediato de hiperacidez gástrica', 'Pirose / Azia aguda', 'Sensação de estômago pesado e gases'],
    contraindications: ['Insuficiência renal grave', 'Espaçar 2 horas da administração de antibióticos e outros fármacos'],
    symptomKeywords: ['azia rapida', 'queimacao agora', 'estomago pesado', 'gases', 'refluxo rapido', 'antiacido', 'mylanta'],
    pregnancyCategory: 'B',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-013',
    name: 'Sais para Reidratação Oral',
    activeSubstance: 'Cloreto de Sódio + Citrato de Potássio + Citrato de Sódio + Glicose',
    tradeNames: ['Rehidroid', 'Hidrafix', 'Pedialyte', 'Floralyte'],
    manufacturer: 'Abbott Laboratories',
    laboratories: ['Abbott', 'EMS', 'Eurofarma', 'Cimed', 'Neo Química', 'Natulab'],
    atcCode: 'ATC_A07CA',
    pharmaceuticalClass: 'Solução Eletrolítica de Reidratação Oral (Fórmula Padrão Ouro OMS)',
    therapeuticClass: 'Reidratantes e Repositores Eletrolíticos',
    pharmaceuticalForms: ['Envelope / Sachê Pó para Reconstituição em 1 Litro', 'Solução Pronta 500ml'],
    usualDosages: ['Sachê 27.9g / 1000ml'],
    defaultPosology: 'Dissolver 1 sachê em 1 litro de água filtrada ou fervida; ingerir pequenos goles após cada evacuação líquida',
    indications: ['Prevenção e tratamento da desidratação em episódios de diarreia aguda e vômitos'],
    contraindications: ['Íleo paralítico', 'Vômitos incoercíveis com incapacidade de deglutição oral'],
    symptomKeywords: ['diarreia', 'desidratacao', 'vomito', 'soro caseiro', 'reidratacao', 'fraqueza desidratado', 'gastroenterite'],
    pregnancyCategory: 'A',
    prescriptionType: 'MIP'
  },

  // ─── CARDIOVASCULARES & METABÓLICOS ───────────────────────────────────────
  {
    id: 'MED-CAN-006',
    name: 'Sildenafila',
    activeSubstance: 'Citrato de Sildenafila',
    tradeNames: ['Viagra', 'Pramil', 'Revatio', 'Soluna', 'Ah-Zul'],
    manufacturer: 'Pfizer',
    laboratories: ['Pfizer', 'EMS', 'Eurofarma', 'Medley', 'Neo Química', 'Cimed', 'Aché'],
    atcCode: 'ATC_G04BE03',
    pharmaceuticalClass: 'Inibidor Seletivo da Fosfodiesterase Tipo 5 (PDE-5)',
    therapeuticClass: 'Vasodilatadores e Agentes para Disfunção Erétil',
    pharmaceuticalForms: ['Comprimido Revestido 25mg', 'Comprimido Revestido 50mg', 'Comprimido Revestido 100mg'],
    usualDosages: ['25mg', '50mg', '100mg'],
    defaultPosology: '50mg via oral aproximadamente 1 hora antes da atividade sexual (máx 1 vez ao dia)',
    indications: ['Disfunção erétil', 'Hipertensão Arterial Pulmonar (Revatio)'],
    contraindications: ['CONTRAINDICAÇÃO ABSOLUTA: Uso concomitante com Nitratos (Monocordil, Sustrate, Nitroglicerina)', 'Angina instável', 'Insuficiência cardíaca grave'],
    symptomKeywords: ['disfuncao eretil', 'impotencia', 'viagra', 'vasodilatador'],
    pregnancyCategory: 'B',
    prescriptionType: 'Sob Prescrição'
  },
  {
    id: 'MED-CAN-007',
    name: 'Isossorbida (Mononitrato / Dinitrato)',
    activeSubstance: 'Mononitrato de Isossorbida / Dinitrato de Isossorbida',
    tradeNames: ['Monocordil', 'Sustrate', 'Isocord', 'Coronur'],
    manufacturer: 'Baldacci / Abbott',
    laboratories: ['Baldacci', 'Abbott', 'EMS', 'Eurofarma', 'Medley'],
    atcCode: 'ATC_C01DA14',
    pharmaceuticalClass: 'Nitrato Vasodilatador Coronariano / Doador de Óxido Nítrico',
    therapeuticClass: 'Vasodilatadores Cardíacos e Antianginosos',
    pharmaceuticalForms: ['Comprimido 20mg', 'Comprimido 40mg', 'Comprimido Sublingual 5mg (Sustrate)'],
    usualDosages: ['5mg', '20mg', '40mg'],
    defaultPosology: '1 comprimido de 20mg a 40mg de 12/12h (com intervalo livre de nitrato de 12h)',
    indications: ['Prevenção e tratamento da Angina Pectoris (Dor no Peito Coronariana)', 'Insuficiência cardíaca congestiva crônica associada'],
    contraindications: ['CONTRAINDICAÇÃO ABSOLUTA com Inibidores de PDE-5 (Sildenafila, Tadalafila)', 'Hipotensão arterial grave', 'Choque cardiogênico'],
    symptomKeywords: ['dor no peito', 'angina', 'coronaria', 'monocordil', 'sustrate', 'infarto prevencao'],
    pregnancyCategory: 'C',
    prescriptionType: 'Sob Prescrição'
  },
  {
    id: 'MED-CAN-008',
    name: 'Losartana Potássica',
    activeSubstance: 'Losartana Potássica',
    tradeNames: ['Aradois', 'Cozaar', 'Losapres', 'Corus', 'Zaarpress'],
    manufacturer: 'Biolab / Organon',
    laboratories: ['Biolab', 'Organon', 'EMS', 'Medley', 'Eurofarma', 'Neo Química', 'Aché', 'Cimed'],
    atcCode: 'ATC_C09CA01',
    pharmaceuticalClass: 'Bloqueador dos Receptores de Angiotensina II (BRA)',
    therapeuticClass: 'Anti-hipertensivos',
    pharmaceuticalForms: ['Comprimido Revestido 50mg', 'Comprimido Revestido 100mg'],
    usualDosages: ['50mg', '100mg'],
    defaultPosology: '50mg a 100mg 1 vez ao dia (pela manhã)',
    indications: ['Hipertensão Arterial Sistêmica', 'Proteção renal em nefropatia diabética tipo 2'],
    contraindications: ['Gravidez (2º e 3º trimestres)', 'Uso concomitante com alisquireno em diabéticos'],
    symptomKeywords: ['pressao alta', 'hipertensao', 'remedio de pressao', 'aradois', 'losartana'],
    pregnancyCategory: 'D',
    prescriptionType: 'Sob Prescrição'
  },
  {
    id: 'MED-CAN-009',
    name: 'Varfarina Sódica',
    activeSubstance: 'Varfarina Sódica',
    tradeNames: ['Marevan', 'Coumadin', 'Varfine'],
    manufacturer: 'Farmoquímica (FQM)',
    laboratories: ['FQM', 'Bristol-Myers Squibb', 'União Química', 'Teuto'],
    atcCode: 'ATC_B01AA03',
    pharmaceuticalClass: 'Anticoagulante Oral Antagonista da Vitamina K',
    therapeuticClass: 'Antitrombóticos e Anticoagulantes',
    pharmaceuticalForms: ['Comprimido 5mg', 'Comprimido 2.5mg'],
    usualDosages: ['2.5mg', '5mg'],
    defaultPosology: 'Dose individualizada ajustada por monitoramento laboratorial de INR (alvo 2.0 a 3.0)',
    indications: ['Prevenção de tromboembolismo venoso (TVP)', 'Embolia pulmonar', 'Prevenção de AVC em Fibrilação Atrial e próteses valvares cardíacas'],
    contraindications: ['Hemorragia ativa grave', 'Uso concomitante com AINEs e salicilatos sem proteção', 'Gravidez'],
    symptomKeywords: ['anticoagulante', 'trombose', 'marevan', 'afinar o sangue', 'fibrilacao atrial', 'tvp'],
    pregnancyCategory: 'X (Contraindicado absoluto na gravidez)',
    prescriptionType: 'Sob Prescrição'
  },
  {
    id: 'MED-CAN-010',
    name: 'Sinvastatina',
    activeSubstance: 'Sinvastatina',
    tradeNames: ['Zocor', 'Sinvasmax', 'Lipitotal', 'Sinvalip'],
    manufacturer: 'Organon',
    laboratories: ['Organon', 'EMS', 'Medley', 'Eurofarma', 'Neo Química', 'Aché', 'Cimed'],
    atcCode: 'ATC_C10AA01',
    pharmaceuticalClass: 'Inibidor da HMG-CoA Redutase (Estatina)',
    therapeuticClass: 'Hipolipemiantes e Redutores de Colesterol',
    pharmaceuticalForms: ['Comprimido Revestido 10mg', 'Comprimido Revestido 20mg', 'Comprimido Revestido 40mg'],
    usualDosages: ['10mg', '20mg', '40mg', '80mg'],
    defaultPosology: '20mg a 40mg via oral 1 vez ao dia à noite',
    indications: ['Hipercolesterolemia primária', 'Prevenção secundária de eventos cardiovasculares ateroscleróticos'],
    contraindications: ['Hepatopatia ativa', 'Gravidez e lactação', 'Uso concomitante com inibidores potentes do CYP3A4 (Claritromicina, Fluconazol)'],
    symptomKeywords: ['colesterol alto', 'colesterol', 'triglicerideos', 'gordura no sangue', 'estatina', 'zocor'],
    pregnancyCategory: 'X',
    prescriptionType: 'Sob Prescrição'
  },

  // ─── ANTIMICROBIANOS & CONTROLADOS ───────────────────────────────────────
  {
    id: 'MED-CAN-014',
    name: 'Amoxicilina',
    activeSubstance: 'Amoxicilina Tri-hidratada',
    tradeNames: ['Amoxil', 'Novocilin', 'Velamox', 'Clavulin (com Clavulanato)'],
    manufacturer: 'GSK / Aché',
    laboratories: ['GSK', 'Aché', 'EMS', 'Medley', 'Eurofarma', 'Neo Química', 'Cimed', 'Teuto'],
    atcCode: 'ATC_J01CA04',
    pharmaceuticalClass: 'Antibacteriano Beta-lactâmico / Aminopenicilina',
    therapeuticClass: 'Antimicrobianos Sistêmicos (RDC 20/2011)',
    pharmaceuticalForms: ['Cápsula 500mg', 'Comprimido 875mg', 'Suspensão Oral 250mg/5ml', 'Suspensão Oral 500mg/5ml'],
    usualDosages: ['500mg', '875mg', '250mg/5ml'],
    defaultPosology: '500mg de 8/8h ou 875mg de 12/12h por 7 a 10 dias consecutivos',
    indications: ['Infecções bacterianas de vias aéreas superiores (Sinusite, Amigdalite, Otite)', 'Infecções respiratórias baixas', 'Infecções urinárias'],
    contraindications: ['Hipersensibilidade grave conhecida a penicilinas e beta-lactâmicos'],
    symptomKeywords: ['infeccao', 'garganta com pus', 'sinusite bacteriana', 'otite', 'antibiotico', 'amoxil'],
    pregnancyCategory: 'B',
    prescriptionType: 'Controlado (RDC 20/2011)'
  },
  {
    id: 'MED-CAN-015',
    name: 'Clonazepam',
    activeSubstance: 'Clonazepam',
    tradeNames: ['Rivotril', 'Navotrax', 'Clopam'],
    manufacturer: 'Roche',
    laboratories: ['Roche', 'EMS', 'Medley', 'Eurofarma', 'Neo Química', 'Aché', 'Teuto'],
    atcCode: 'ATC_N03AE01',
    pharmaceuticalClass: 'Benzodiazepínico Depressor do SNC / Agonista GABA-A',
    therapeuticClass: 'Ansiolíticos e Anticonvulsivantes (Portaria 344/98 - Lista B1)',
    pharmaceuticalForms: ['Comprimido 0.5mg', 'Comprimido 2.0mg', 'Comprimido Sublingual 0.25mg', 'Solução Oral Gotas 2.5mg/ml'],
    usualDosages: ['0.25mg', '0.5mg', '2.0mg', '2.5mg/ml'],
    defaultPosology: '0.5mg a 2.0mg à noite antes de dormir conforme prescrição médica',
    indications: ['Transtornos de ansiedade e pânico', 'Insônia refratária transitória', 'Crises epilépticas'],
    contraindications: ['Miastenia gravis', 'Insuficiência respiratória grave', 'Apneia do sono', 'Uso concomitante com álcool ou opioides'],
    symptomKeywords: ['ansiedade', 'panico', 'calmante', 'insonia', 'rivotril', 'crise de ansiedade', 'remedio tarja preta'],
    pregnancyCategory: 'D',
    prescriptionType: 'Controlado B1 (Portaria 344/98)'
  },
  
  // ─── XAROPES, EXPECTORANTES & ANTITUSSÍGENOS (MIPs) ──────────────────────
  {
    id: 'MED-CAN-020',
    name: 'Dropropizina (Xarope)',
    activeSubstance: 'Dropropizina',
    tradeNames: ['Vibral', 'Notuss', 'Atoss', 'Drotoss', 'Silencium'],
    manufacturer: 'EMS / Aché',
    laboratories: ['EMS', 'Aché', 'Eurofarma', 'Medley', 'Neo Química', 'Cimed', 'Teuto'],
    atcCode: 'ATC_R05DB',
    pharmaceuticalClass: 'Antitussígeno de Ação Periférica (Não Opiáceo)',
    therapeuticClass: 'Antitussígenos e Sedativos da Tosse Seca',
    pharmaceuticalForms: ['Xarope Adulto 3mg/ml (Frasco 120ml)', 'Xarope Pediátrico 1.5mg/ml (Frasco 120ml)'],
    usualDosages: ['3mg/ml', '1.5mg/ml'],
    defaultPosology: 'Adultos: 10ml (1 copo-medida) 3 a 4 vezes ao dia. Crianças: 5ml a 10ml conforme faixa etária.',
    indications: ['Tosse seca irritativa', 'Tosse noturna sem expectoração', 'Irritação traqueobrônquica pós-viral'],
    contraindications: ['Hipersensibilidade à dropropizina', 'Insuficiência respiratória grave', 'Crianças < 2 anos'],
    symptomKeywords: ['xarope', 'xaropes', 'tosse seca', 'tosse irritativa', 'vibral', 'notuss', 'tosse noturna', 'xarope tosse'],
    pregnancyCategory: 'C',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-021',
    name: 'Acebrofilina (Xarope)',
    activeSubstance: 'Acebrofilina',
    tradeNames: ['Brondilat', 'Filinar', 'Acebrofil', 'Bronfil'],
    manufacturer: 'Aché / Eurofarma',
    laboratories: ['Aché', 'Eurofarma', 'EMS', 'Medley', 'Neo Química', 'Cimed'],
    atcCode: 'ATC_R03DA14',
    pharmaceuticalClass: 'Mucorregulador, Broncodilatador e Expectorante',
    therapeuticClass: 'Broncodilatadores e Mucolíticos',
    pharmaceuticalForms: ['Xarope Adulto 10mg/ml (Frasco 120ml)', 'Xarope Pediátrico 5mg/ml (Frasco 120ml)'],
    usualDosages: ['10mg/ml', '5mg/ml'],
    defaultPosology: 'Adultos: 10ml de 12/12 horas. Crianças acima de 2 anos: 5ml de 12/12 horas.',
    indications: ['Tosse produtiva com chiado no peito', 'Bronquite obstrutiva', 'Catarro espesso com dificuldade respiratória'],
    contraindications: ['Hipersensibilidade a derivados de xantinas', 'Doença hepática ou renal grave', 'Crianças < 2 anos'],
    symptomKeywords: ['xarope', 'xaropes', 'acebrofilina', 'brondilat', 'tosse com chiado', 'bronquite', 'expectorante forte', 'peito cheio'],
    pregnancyCategory: 'C',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-022',
    name: 'Guaifenesina + Mel (Xarope)',
    activeSubstance: 'Guaifenesina (Guaiacolato de Glicerila)',
    tradeNames: ['Vick Xarope', 'Xarope Transpulmin', 'Bisolvon', 'Iodepol'],
    manufacturer: 'Procter & Gamble (P&G)',
    laboratories: ['P&G', 'Sanofi', 'EMS', 'Cimed', 'Neo Química', 'Boehringer Ingelheim'],
    atcCode: 'ATC_R05CA03',
    pharmaceuticalClass: 'Expectorante Fluidificante Direto',
    therapeuticClass: 'Expectorantes e Fluidificantes de Muco',
    pharmaceuticalForms: ['Xarope Adulto 13.33mg/ml (Frasco 120ml)', 'Xarope Pediátrico 6.67mg/ml (Frasco 120ml)'],
    usualDosages: ['13.33mg/ml', '6.67mg/ml'],
    defaultPosology: '15ml (1 colher de sopa) a cada 4 horas conforme necessidade (máximo 6 doses/dia).',
    indications: ['Alívio da tosse com secreção', 'Fluidificação e eliminação de catarro em gripes e resfriados'],
    contraindications: ['Hipersensibilidade à guaifenesina', 'Tosse crônica do tabagismo ou asma'],
    symptomKeywords: ['xarope', 'xaropes', 'vick xarope', 'expectorante', 'catarro', 'tosse cheia', 'limpar catarro', 'mel e limao'],
    pregnancyCategory: 'C',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-023',
    name: 'Hedera Helix (Xarope Fitoterápico)',
    activeSubstance: 'Extrato Seco de Folhas de Hedera Helix L.',
    tradeNames: ['Abrilar', 'Heletux', 'Tossclin', 'Kaloba Tosse'],
    manufacturer: 'Farmoquímica (FQM)',
    laboratories: ['Farmoquímica', 'Eurofarma', 'Herbarium', 'Apsen'],
    atcCode: 'ATC_R05CA',
    pharmaceuticalClass: 'Fitoterápico Mucolítico, Espasmolítico e Broncodilatador',
    therapeuticClass: 'Fitoterápicos Respiratórios e Expectorantes',
    pharmaceuticalForms: ['Xarope Solução Oral 7mg/ml (Frasco 100ml / 200ml)'],
    usualDosages: ['7mg/ml'],
    defaultPosology: 'Adultos: 5ml a 7.5ml 3 vezes ao dia. Crianças de 2 a 5 anos: 2.5ml 2 vezes ao dia.',
    indications: ['Tratamento sintomático de doenças inflamatórias crônicas e agudas das vias respiratórias com tosse'],
    contraindications: ['Hipersensibilidade à substância ativa ou a outras plantas da família Araliaceae', 'Gravidez e lactação'],
    symptomKeywords: ['xarope', 'xaropes', 'abrilar', 'fitoterapico tosse', 'xarope natural', 'hedera helix', 'tosse infantil fitoterapico'],
    pregnancyCategory: 'C',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-024',
    name: 'Lactulose (Xarope)',
    activeSubstance: 'Lactulose 667mg/ml',
    tradeNames: ['Lactulona', 'Farlac', 'Duphalac', 'Pentalac'],
    manufacturer: 'Daiichi Sankyo / Abbott',
    laboratories: ['Daiichi Sankyo', 'Abbott', 'EMS', 'Eurofarma', 'Medley', 'Neo Química', 'Cimed'],
    atcCode: 'ATC_A06AD11',
    pharmaceuticalClass: 'Laxativo Osmótico e Pré-biótico',
    therapeuticClass: 'Laxativos e Reguladores Intestinais',
    pharmaceuticalForms: ['Xarope Solução Oral 667mg/ml (Frasco 120ml / 200ml)'],
    usualDosages: ['667mg/ml'],
    defaultPosology: '15ml a 30ml ao dia em dose única pela manhã ou dividida em 2 tomadas.',
    indications: ['Constipação intestinal crônica e aguda', 'Prevenção e tratamento de encefalopatia hepática', 'Regulação da flora'],
    contraindications: ['Galactosemia', 'Obstrução intestinal mecânica', 'Apendicite'],
    symptomKeywords: ['xarope', 'xaropes', 'prisao de ventre', 'constipacao', 'intestino preso', 'lactulona', 'lactulose', 'soltar intestino'],
    pregnancyCategory: 'B',
    prescriptionType: 'MIP'
  },

  // ─── ANALGÉSICOS POPULARES, COMBINAÇÕES & ENXAQUECA ──────────────────────
  {
    id: 'MED-CAN-025',
    name: 'Dipirona + Isometepteno + Cafeína',
    activeSubstance: 'Dipirona 300mg + Mucato de Isometepteno 30mg + Cafeína 30mg',
    tradeNames: ['Neosaldina', 'Doralgina', 'Neosulida', 'Sedalgina', 'Dorbel', 'Cefalium'],
    manufacturer: 'Takeda / Brainfarma / Hypera Pharma',
    laboratories: ['Takeda', 'Hypera Pharma', 'EMS', 'Neo Química', 'Cimed', 'Eurofarma'],
    atcCode: 'ATC_N02BB72',
    pharmaceuticalClass: 'Analgésico Combinado com Vasoconstritor Cerebral e Estimulante',
    therapeuticClass: 'Antienxaquecosos e Analgésicos Específicos para Cefaleia',
    pharmaceuticalForms: ['Drágea', 'Solução Oral Gotas 15ml / 30ml'],
    usualDosages: ['1 a 2 drágeas', '30 a 60 gotas'],
    defaultPosology: '1 a 2 drágeas de 6/6h ou se crise de enxaqueca (máx 8 drágeas/dia)',
    indications: ['Cefaleia tensional', 'Enxaqueca aguda com dor pulsátil', 'Cefaleia vascular'],
    contraindications: ['Hipertensão arterial grave ou descompensada', 'Glaucoma', 'Alergia a dipirona'],
    symptomKeywords: ['neosaldina', 'doralgina', 'enxaqueca', 'dor de cabeca forte', 'cabeca latejando', 'isometepteno', 'cafeina', 'dor na testa'],
    pregnancyCategory: 'C',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-026',
    name: 'Paracetamol + Carisoprodol + Cafeína + Diclofenaco',
    activeSubstance: 'Paracetamol 300mg + Cafeína 30mg + Carisoprodol 125mg + Diclofenaco Sódico 50mg',
    tradeNames: ['Tandrilax', 'Mioflex A', 'Dorilax Forte', 'Beserol', 'Alginac'],
    manufacturer: 'Aché / Sanofi',
    laboratories: ['Aché', 'Sanofi', 'EMS', 'Eurofarma', 'Neo Química', 'Cimed'],
    atcCode: 'ATC_M01AB55',
    pharmaceuticalClass: 'Anti-inflamatório, Analgésico e Miorrelaxante Quádruplo',
    therapeuticClass: 'Relaxantes Musculares e Anti-inflamatórios Potentes',
    pharmaceuticalForms: ['Comprimido'],
    usualDosages: ['1 comprimido'],
    defaultPosology: '1 comprimido a cada 12 horas ou 8 horas após refeição (máx 3 comp/dia por até 5 dias)',
    indications: ['Lumbago', 'Lombociatalgia', 'Torcicolo grave', 'Espasmos musculares pós-traumáticos'],
    contraindications: ['Úlcera gástrica ativa', 'Insuficiência renal grave', 'Porfiria'],
    symptomKeywords: ['tandrilax', 'mioflex', 'dor nas costas travada', 'coluna travada', 'nervo ciatico', 'lombalgia forte', 'pescoco duro', 'dor muscular intensa'],
    pregnancyCategory: 'D',
    prescriptionType: 'Sob Prescrição'
  },
  {
    id: 'MED-CAN-027',
    name: 'Trometamol Cetorolaco (Sublingual)',
    activeSubstance: 'Trometamol Cetorolaco',
    tradeNames: ['Toragesic', 'Deocil', 'Cetoclin', 'Algitec'],
    manufacturer: 'EMS / Ache',
    laboratories: ['EMS', 'Aché', 'Eurofarma', 'Cimed', 'Neo Química'],
    atcCode: 'ATC_M01AB15',
    pharmaceuticalClass: 'Anti-inflamatório Não Esteroidal Potente (AINE) Inibidor COX',
    therapeuticClass: 'Analgésicos de Ação Rápida e Potente',
    pharmaceuticalForms: ['Comprimido Sublingual 10mg', 'Comprimido Sublingual 20mg', 'Gotas 20mg/ml'],
    usualDosages: ['10mg sublingual'],
    defaultPosology: '1 comprimido de 10mg sublingual a cada 6 a 8 horas (máximo 40mg/dia e uso por no máx 5 dias)',
    indications: ['Dor aguda de intensidade moderada a forte', 'Pós-operatório odontológico', 'Crise aguda de dor de dente ou cólica renal'],
    contraindications: ['Úlcera péptica ativa', 'Distúrbios de coagulação', 'Insuficiência renal moderada a grave', 'Gestação e parto'],
    symptomKeywords: ['toragesic', 'deocil', 'cetorolaco', 'dor de dente insuportavel', 'canal dente', 'pos operatorio', 'dor aguda forte'],
    pregnancyCategory: 'C (D no 3º trimestre)',
    prescriptionType: 'Sob Prescrição'
  },
  {
    id: 'MED-CAN-028',
    name: 'Naproxeno Sódico',
    activeSubstance: 'Naproxeno Sódico',
    tradeNames: ['Flanax', 'Naproche', 'Naxotec', 'Aleve'],
    manufacturer: 'Bayer',
    laboratories: ['Bayer', 'EMS', 'Eurofarma', 'Medley', 'Neo Química', 'Cimed'],
    atcCode: 'ATC_M01AE02',
    pharmaceuticalClass: 'Anti-inflamatório Não Esteroidal com Longa Meia-Vida',
    therapeuticClass: 'Anti-inflamatórios e Analgésicos Sistêmicos',
    pharmaceuticalForms: ['Comprimido Revestido 275mg', 'Comprimido Revestido 550mg'],
    usualDosages: ['275mg', '550mg'],
    defaultPosology: '1 comprimido de 550mg 1 a 2 vezes ao dia com alimentos',
    indications: ['Dor de garganta com inflamação', 'Tendinite e sinusite', 'Dismenorreia / cólica menstrual'],
    contraindications: ['Hipersensibilidade ao ácido acetilsalicílico ou outros AINEs', 'Úlcera péptica'],
    symptomKeywords: ['flanax', 'naproxeno', 'garganta inflamada', 'dor de garganta forte', 'colica menstrual', 'inflamacao dente'],
    pregnancyCategory: 'C',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-029',
    name: 'Nimesulida',
    activeSubstance: 'Nimesulida',
    tradeNames: ['Nisulid', 'Cimelide', 'Maxsulid', 'Scaflam', 'Nimesil'],
    manufacturer: 'Aché / Cimed',
    laboratories: ['Aché', 'Cimed', 'EMS', 'Medley', 'Eurofarma', 'Neo Química', 'Teuto'],
    atcCode: 'ATC_M01AX17',
    pharmaceuticalClass: 'Anti-inflamatório Inibidor Preferencial da COX-2',
    therapeuticClass: 'Anti-inflamatórios Sistêmicos',
    pharmaceuticalForms: ['Comprimido 100mg', 'Suspensão Gotas 50mg/ml', 'Gel Tópico 2%'],
    usualDosages: ['100mg', '50mg/ml'],
    defaultPosology: '1 comprimido de 100mg (ou 40 gotas) de 12/12h após as refeições (por até 5 a 7 dias)',
    indications: ['Inflamação de garganta e ouvido', 'Dor pós-traumática', 'Osteoartrite e dores articulares'],
    contraindications: ['Insuficiência hepática ou histórico de hepatotoxicidade', 'Úlcera ativa', 'Crianças < 12 anos'],
    symptomKeywords: ['nimesulida', 'nisulid', 'cimelide', 'garganta inflamada', 'dor no ouvido', 'dor no dente', 'anti-inflamatorio'],
    pregnancyCategory: 'C (D no 3º trimestre)',
    prescriptionType: 'Sob Prescrição'
  },

  // ─── GASTROINTESTINAIS, ANTIEMÉTICOS & DIGESTIVOS ─────────────────────────
  {
    id: 'MED-CAN-030',
    name: 'Cloridrato de Ondansetrona',
    activeSubstance: 'Cloridrato de Ondansetrona Di-hidratado',
    tradeNames: ['Vonau Flash', 'Zofran', 'Nausicalm', 'Nausedron'],
    manufacturer: 'Biolab / GSK',
    laboratories: ['Biolab', 'GSK', 'EMS', 'Eurofarma', 'Medley', 'Neo Química', 'Cimed'],
    atcCode: 'ATC_A04AA01',
    pharmaceuticalClass: 'Antagonista Seletivo dos Receptores 5-HT3 de Serotonina',
    therapeuticClass: 'Antieméticos Potentes e Reguladores do Centro do Vômito',
    pharmaceuticalForms: ['Comprimido Dissolução Rápida (Flash) 4mg', 'Comprimido Flash 8mg', 'Gotas 4mg/ml'],
    usualDosages: ['4mg', '8mg', '4mg/ml'],
    defaultPosology: '1 comprimido de 4mg a 8mg dissolvido diretamente na língua de 8/8h conforme náusea',
    indications: ['Prevenção e controle de náuseas e vômitos agudos', 'Gastroenterite viral', 'Enjoo alimentar'],
    contraindications: ['Uso concomitante com Apomorfina', 'Prolongamento congênito do intervalo QT'],
    symptomKeywords: ['vonau', 'zofran', 'ondansetrona', 'enjoo', 'vomito', 'ansia de vomito', 'nausea', 'enjoo forte', 'gastroenterite'],
    pregnancyCategory: 'B',
    prescriptionType: 'MIP / Sob Prescrição'
  },
  {
    id: 'MED-CAN-031',
    name: 'Dimenidrinato + Piridoxina',
    activeSubstance: 'Dimenidrinato 50mg + Cloridrato de Piridoxina (Vitamina B6) 10mg',
    tradeNames: ['Dramin', 'Dramin B6', 'Dramavit', 'Nausilon'],
    manufacturer: 'Takeda / Hypera Pharma',
    laboratories: ['Takeda', 'Hypera Pharma', 'EMS', 'Eurofarma', 'Cimed', 'Neo Química'],
    atcCode: 'ATC_A04AD',
    pharmaceuticalClass: 'Anti-histamínico H1 com Ação Antiemética e Antivertiginosa',
    therapeuticClass: 'Antieméticos e Antivertiginosos para Enjoo de Viagem (Cinetose)',
    pharmaceuticalForms: ['Comprimido Revestido', 'Gotas Pediátricas e Adulto', 'Cápsula Gel'],
    usualDosages: ['1 comprimido', '20 a 40 gotas'],
    defaultPosology: '1 comprimido de 6/6h ou 30 minutos antes de viagens (máximo 400mg/dia)',
    indications: ['Cinetose (enjoo de movimento/carro/barco/avião)', 'Labirintite com tontura e náusea', 'Enjoo de gestante (sob orientação)'],
    contraindications: ['Glaucoma', 'Retenção urinária', 'Crise de asma aguda'],
    symptomKeywords: ['dramin', 'dramin b6', 'enjoo de viagem', 'labirintite', 'tontura', 'cinetose', 'ansia no carro', 'barco enjoo'],
    pregnancyCategory: 'B',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-032',
    name: 'Simeticona',
    activeSubstance: 'Simeticona (Dimeticona Ativada)',
    tradeNames: ['Luftal', 'Flagass', 'Mylicon', 'Flatex', 'Gasvital'],
    manufacturer: 'Reckitt Benckiser / Aché',
    laboratories: ['Reckitt Benckiser', 'Aché', 'EMS', 'Medley', 'Eurofarma', 'Neo Química', 'Cimed'],
    atcCode: 'ATC_A03AX13',
    pharmaceuticalClass: 'Agente Antiespumante Tensoativo / Antiflatulento',
    therapeuticClass: 'Antiflatulentos e Redutores de Gases Gastrointestinais',
    pharmaceuticalForms: ['Comprimido 40mg', 'Cápsula Gelatinosa 125mg (Luftal Max)', 'Solução Gotas 75mg/ml'],
    usualDosages: ['40mg', '125mg', '75mg/ml'],
    defaultPosology: '1 comprimido ou 1 cápsula de 125mg de 8/8h após as refeições (ou 30 gotas 3x ao dia)',
    indications: ['Excesso de gases no aparelho digestivo', 'Sensação de estufamento e barriga inchada', 'Cólicas por flatulência'],
    contraindications: ['Suspeita de perfuração ou obstrução intestinal mecânica'],
    symptomKeywords: ['luftal', 'simeticona', 'gases', 'barriga inchada', 'estufamento', 'flatus', 'peito cheio de ar', 'colica por gases'],
    pregnancyCategory: 'A',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-033',
    name: 'Saccharomyces boulardii (Probiótico)',
    activeSubstance: 'Saccharomyces boulardii-17 liofilizado',
    tradeNames: ['Floratil', 'Repoflor', 'Florax', 'Levenew'],
    manufacturer: 'Biocodex / Farmoquímica (FQM)',
    laboratories: ['Biocodex', 'FQM', 'Eurofarma', 'EMS', 'Apsen', 'Cimed'],
    atcCode: 'ATC_A07FA02',
    pharmaceuticalClass: 'Probiótico / Levedura Terapêutica Biorreguladora da Microbiota',
    therapeuticClass: 'Antidiarreicos e Restauradores da Flora Intestinal',
    pharmaceuticalForms: ['Cápsula 100mg', 'Cápsula 200mg', 'Envelope Sachê Pó Oral 200mg'],
    usualDosages: ['100mg', '200mg'],
    defaultPosology: '1 cápsula ou 1 sachê de 200mg 2 vezes ao dia dissolvido em água ou suco',
    indications: ['Restauração da flora intestinal em diarreia aguda', 'Prevenção de diarreia associada a antibióticos'],
    contraindications: ['Pacientes portadores de cateter venoso central (risco de fungemia)'],
    symptomKeywords: ['floratil', 'repoflor', 'probiotico', 'flora intestinal', 'diarreia antibiotico', 'desarranjo intestinal', 'regular intestino'],
    pregnancyCategory: 'A',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-034',
    name: 'Sal de Fruta Eno / Antiácido Efervescente',
    activeSubstance: 'Bicarbonato de Sódio + Carbonato de Sódio + Ácido Cítrico',
    tradeNames: ['Sal de Fruta Eno', 'Estomazil', 'Sonrisal', 'Engov After'],
    manufacturer: 'Haleon / Hypera Pharma',
    laboratories: ['Haleon', 'Hypera Pharma', 'Cimed', 'EMS'],
    atcCode: 'ATC_A02AH',
    pharmaceuticalClass: 'Antiácido Efervescente Neutralizante Químico Imediato',
    therapeuticClass: 'Antiácidos e Alívio Rápido de Azia e Má Digestão',
    pharmaceuticalForms: ['Envelope Sachê 5g Pó Efervescente', 'Frasco 100g'],
    usualDosages: ['1 sachê (5g)'],
    defaultPosology: 'Dissolver 1 sachê em meio copo de água e beber imediatamente durante a efervescência',
    indications: ['Alívio rápido da azia, má digestão, queimação estomacal e sensação de peso'],
    contraindications: ['Dieta restrita de sódio', 'Insuficiência cardíaca ou renal descompensada'],
    symptomKeywords: ['sal de fruta eno', 'estomazil', 'sonrisal', 'azia rapida', 'queimacao estomago', 'ma digestao', 'ressaca', 'estomago pesado'],
    pregnancyCategory: 'B',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-035',
    name: 'Epocler / Citrato de Colina + Betaína + Metionina',
    activeSubstance: 'Citrato de Colina + Betaína + Racemetionina',
    tradeNames: ['Epocler', 'Hepatilon', 'Xantinon', 'Hepa-Merz'],
    manufacturer: 'Hypera Pharma',
    laboratories: ['Hypera Pharma', 'Eurofarma', 'EMS', 'Cimed', 'Natulab'],
    atcCode: 'ATC_A05BA',
    pharmaceuticalClass: 'Hepatoprotetor e Desintoxicante Hepático Metabólico',
    therapeuticClass: 'Protetores Hepáticos e Digestivos',
    pharmaceuticalForms: ['Flaconete Bebível 10ml', 'Comprimido Drágea'],
    usualDosages: ['1 flaconete (10ml)'],
    defaultPosology: '1 flaconete até 3 vezes ao dia antes das principais refeições ou após excessos alimentares',
    indications: ['Tratamento de distúrbios metabólicos hepáticos', 'Má digestão e mal-estar pós-ingestão de gorduras e álcool'],
    contraindications: ['Hipersensibilidade aos componentes da fórmula'],
    symptomKeywords: ['epocler', 'figado atacado', 'remedio pro figado', 'hepatilon', 'xantinon', 'ressaca alimentar', 'gordura pesada'],
    pregnancyCategory: 'B',
    prescriptionType: 'MIP'
  },

  // ─── GRIPES, IMUNIDADE & FITOTERÁPICOS ────────────────────────────────────
  {
    id: 'MED-CAN-036',
    name: 'Dipirona + Maleato de Clorfeniramina + Cafeína (Antigripal)',
    activeSubstance: 'Dipirona 500mg + Maleato de Clorfeniramina 2mg + Cafeína 30mg',
    tradeNames: ['Benegrip', 'Resfenol', 'Cimegripe', 'Flucol', 'Gripin'],
    manufacturer: 'Hypera Pharma / Cimed',
    laboratories: ['Hypera Pharma', 'Cimed', 'EMS', 'Eurofarma', 'Neo Química', 'Kley Hertz'],
    atcCode: 'ATC_N02BB72',
    pharmaceuticalClass: 'Antigripal Combinado (Analgésico, Anti-histamínico e Estimulante)',
    therapeuticClass: 'Antigripais Sistêmicos para Congestão, Dor e Febre',
    pharmaceuticalForms: ['Comprimido Revestido (Verde e Amarelo)', 'Cápsula', 'Gotas'],
    usualDosages: ['1 a 2 comprimidos'],
    defaultPosology: '1 comprimido verde + 1 amarelo a cada 6 a 8 horas (máximo 4 doses ao dia)',
    indications: ['Alívio dos sintomas de gripes e resfriados (dor de cabeça, febre, coriza, dores musculares)'],
    contraindications: ['Alergia a dipirona', 'Glaucoma de ângulo fechado', 'Hipertensão severa'],
    symptomKeywords: ['benegrip', 'cimegripe', 'resfenol', 'antigripal', 'remedio de gripe', 'coriza e dor', 'gripe forte', 'febre e moleza'],
    pregnancyCategory: 'C',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-037',
    name: 'Extrato Seco de Passiflora incarnata (Calmante Natural)',
    activeSubstance: 'Extrato Seco Padronizado de Passiflora incarnata L. 300mg / 500mg',
    tradeNames: ['Maracugina', 'Seakalm', 'Calman', 'Passiflorine', 'Ritmoneuran'],
    manufacturer: 'Hypera Pharma / Natulab',
    laboratories: ['Hypera Pharma', 'Natulab', 'Herbarium', 'Eurofarma', 'Cimed', 'Apsen'],
    atcCode: 'ATC_N05CM',
    pharmaceuticalClass: 'Fitoterápico Ansiolítico e Sedativo Leve (Agonista Receptores GABA)',
    therapeuticClass: 'Fitoterápicos Ansiolíticos, Calmantes e Indutores do Sono',
    pharmaceuticalForms: ['Comprimido Revestido 300mg / 500mg', 'Solução Oral Gotas'],
    usualDosages: ['300mg', '500mg'],
    defaultPosology: '1 comprimido de 300mg a 500mg 1 a 2 vezes ao dia ou 30 minutos antes de dormir',
    indications: ['Quadros leves de ansiedade, agitação e estresse', 'Irritabilidade', 'Dificuldade para conciliar o sono'],
    contraindications: ['Hipersensibilidade ao maracujá/passiflora', 'Uso concomitante com bebidas alcoólicas'],
    symptomKeywords: ['maracugina', 'seakalm', 'calmante natural', 'passiflora', 'calman', 'ansiedade leve', 'estresse', 'nervoso', 'dormir natural'],
    pregnancyCategory: 'C',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-038',
    name: 'Vitamina C (Ácido Ascórbico)',
    activeSubstance: 'Ácido Ascórbico 500mg / 1000mg',
    tradeNames: ['Redoxon', 'Cewin', 'C-Targ', 'Cebion', 'Vit Cimed'],
    manufacturer: 'Bayer / Sanofi',
    laboratories: ['Bayer', 'Sanofi', 'Cimed', 'EMS', 'Eurofarma', 'Neo Química'],
    atcCode: 'ATC_A11GA01',
    pharmaceuticalClass: 'Vitamina Hidrossolúvel Antioxidante e Imunoestimulante',
    therapeuticClass: 'Vitaminas e Suplementos Imunológicos',
    pharmaceuticalForms: ['Comprimido Efervescente 1g', 'Comprimido Mastigável 500mg', 'Gotas 200mg/ml'],
    usualDosages: ['500mg', '1g'],
    defaultPosology: '1 comprimido efervescente de 1g dissolvido em um copo de água 1 vez ao dia pela manhã',
    indications: ['Reforço do sistema imunológico', 'Suplementação em gripes e pós-infecções', 'Cicatrizante'],
    contraindications: ['Histórico de cálculos renais por oxalato de cálcio', 'Hemocromatose'],
    symptomKeywords: ['vitamina c', 'redoxon', 'cewin', 'acido ascorbico', 'imunidade', 'resistencia', 'gripe vitamina', 'vitamina efervescente'],
    pregnancyCategory: 'A',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-039',
    name: 'Vitamina D3 (Colecalciferol)',
    activeSubstance: 'Colecalciferol (Vitamina D3)',
    tradeNames: ['Addera D3', 'Depura', 'D-Vit', 'Sanval D3', 'Doss'],
    manufacturer: 'Hypera Pharma / Sanofi',
    laboratories: ['Hypera Pharma', 'Sanofi', 'Eurofarma', 'EMS', 'Aché', 'Cimed'],
    atcCode: 'ATC_A11CC05',
    pharmaceuticalClass: 'Secoesteroide Regulador do Metabolismo Fosfocálcico e Imunológico',
    therapeuticClass: 'Vitaminas e Suplementos Ósseos / Imunomoduladores',
    pharmaceuticalForms: ['Gotas 200 UI/gota', 'Cápsula 1.000 UI', 'Cápsula 2.000 UI', 'Cápsula 7.000 UI', 'Cápsula 50.000 UI'],
    usualDosages: ['1.000 UI', '2.000 UI', '7.000 UI/semana', '50.000 UI'],
    defaultPosology: '1.000 UI a 2.000 UI ao dia com a refeição principal (ou 50.000 UI 1x/semana em deficiência)',
    indications: ['Prevenção e tratamento de hipovitaminose D', 'Osteoporose e saúde óssea', 'Modulação imune'],
    contraindications: ['Hipercalcemia', 'Hipervitaminose D', 'Osteodistrofia renal com hiperfosfatemia'],
    symptomKeywords: ['vitamina d', 'vitamina d3', 'addera d3', 'depura', 'colecalciferol', 'imunidade d3', 'ossos fracos', 'falta de sol'],
    pregnancyCategory: 'A',
    prescriptionType: 'MIP / Sob Prescrição'
  },
  {
    id: 'MED-CAN-040',
    name: 'Metformina (Antidiabético Oral)',
    activeSubstance: 'Cloridrato de Metformina',
    tradeNames: ['Glifage', 'Glifage XR', 'Glucoformin', 'Dimefor'],
    manufacturer: 'Merck / EMS',
    laboratories: ['Merck', 'EMS', 'Medley', 'Eurofarma', 'Neo Química', 'Cimed', 'Aché', 'Prati-Donaduzzi'],
    atcCode: 'ATC_A10BA02',
    pharmaceuticalClass: 'Biguanida Sensibilizadora da Insulina',
    therapeuticClass: 'Antidiabéticos Orais e Hipoglicemiantes',
    pharmaceuticalForms: ['Comprimido 500mg', 'Comprimido 850mg', 'Comprimido Liberação Prolongada 500mg / 750mg / 1000mg XR'],
    usualDosages: ['500mg', '850mg', '1000mg XR'],
    defaultPosology: '500mg a 1000mg 1 a 2 vezes ao dia durante ou imediatamente após as principais refeições',
    indications: ['Diabetes Mellitus Tipo 2', 'Resistência insulínica e Síndrome dos Ovários Policísticos (SOP)'],
    contraindications: ['Insuficiência renal moderada a grave (TFGe < 30 ml/min)', 'Acidose láctica'],
    symptomKeywords: ['metformina', 'glifage', 'diabetes', 'remedio de diabetes', 'acucar no sangue', 'glicemia alta', 'glicose'],
    pregnancyCategory: 'B',
    prescriptionType: 'Sob Prescrição'
  },
  {
    id: 'MED-CAN-041',
    name: 'Levotiroxina Sódica (Hormônio Tireoidiano)',
    activeSubstance: 'Levotiroxina Sódica (T4 Sintético)',
    tradeNames: ['Puran T4', 'Synthroid', 'Levoid', 'Euthyrox'],
    manufacturer: 'Sanofi / Abbott / Merck',
    laboratories: ['Sanofi', 'Abbott', 'Merck', 'EMS'],
    atcCode: 'ATC_H03AA01',
    pharmaceuticalClass: 'Hormônio Tireoidiano Sintético Levógiro',
    therapeuticClass: 'Hormônios Tireoidianos e Terapia de Reposição',
    pharmaceuticalForms: ['Comprimido 25mcg', '50mcg', '75mcg', '88mcg', '100mcg', '112mcg', '125mcg', '150mcg'],
    usualDosages: ['25mcg', '50mcg', '75mcg', '100mcg', '125mcg'],
    defaultPosology: 'Tomar a dose prescrita pela manhã em jejum absoluto com água, 30 a 60 minutos antes do café da manhã',
    indications: ['Hipotireoidismo primário e secundário', 'Reposição após tireoidectomia', 'Supressão do TSH'],
    contraindications: ['Tireotoxicose não tratada', 'Infarto agudo do miocárdio recente', 'Insuficiência adrenal descompensada'],
    symptomKeywords: ['puran t4', 'synthroid', 'levotiroxina', 'tireoide', 'hipotireoidismo', 'remedio de tireoide', 't4 livre', 'tsh'],
    pregnancyCategory: 'A (Essencial manutenção na gestação)',
    prescriptionType: 'Sob Prescrição'
  }
];
