// ==========================================================================
// 🌿 HEALTH NEXUS — BASE CANÔNICA DE MEDICAMENTOS & FARMACOLOGIA (ANVISA / DCB)
// Catálogo farmacoterapêutico de referência para busca, triagem e cruzamento
// ==========================================================================

export const CANONICAL_MEDICATIONS_DB = [
  // ─── ANALGÉSICOS, ANTITÉRMICOS & ANTI-INFLAMATÓRIOS ───────────────────────
  {
    id: 'MED-CAN-001',
    name: 'Dipirona Monoidratada',
    activeSubstance: 'Dipirona Monoidratada (Metamizol)',
    tradeNames: ['Novalgina', 'Anador', 'Lisador', 'Doralgina', 'Maxiliv'],
    atcCode: 'ATC_N02BB02',
    pharmaceuticalClass: 'Analgésico e Antitérmico Derivado das Pirazolonas',
    therapeuticClass: 'Analgésicos e Antitérmicos',
    pharmaceuticalForms: ['Comprimido 500mg', 'Comprimido 1g', 'Solução Oral Gotas 500mg/ml', 'Ampola Injetável 500mg/ml'],
    usualDosages: ['500mg', '1g', '500mg/ml'],
    defaultPosology: '1 comprimido de 500mg a 1g a cada 6 horas se dor ou febre (máx 4g/dia)',
    indications: ['Dor aguda de intensidade leve a moderada', 'Febre refratária', 'Cefaleia', 'Dor pós-operatória'],
    contraindications: ['Hipersensibilidade a pirazolonas', 'Porfiria hepática aguda', 'Deficiência congênita de G6PD', 'Gravidez no 3º trimestre'],
    symptomKeywords: ['dor', 'febre', 'dor de cabeca', 'cefaleia', 'mialgia', 'dor no corpo', 'gripe', 'moleza', 'enxaqueca'],
    pregnancyCategory: 'C',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-002',
    name: 'Paracetamol',
    activeSubstance: 'Paracetamol (Acetaminofeno)',
    tradeNames: ['Tylenol', 'Dôrico', 'Parador', 'Cimegripe', 'Resfenol'],
    atcCode: 'ATC_N02BE01',
    pharmaceuticalClass: 'Analgésico e Antitérmico Derivado do Para-aminofenol',
    therapeuticClass: 'Analgésicos e Antitérmicos',
    pharmaceuticalForms: ['Comprimido 500mg', 'Comprimido 750mg', 'Suspensão Gotas 200mg/ml', 'Xarope 32mg/ml'],
    usualDosages: ['500mg', '750mg', '200mg/ml'],
    defaultPosology: '1 comprimido de 500mg a 750mg de 6/6h ou 8/8h (dose máxima 3g a 4g/dia)',
    indications: ['Alívio de dores leves a moderadas', 'Redução da febre em adultos e crianças', 'Opção de 1ª linha em gestantes e dengue'],
    contraindications: ['Hepatopatia grave / Insuficiência hepática', 'Uso concomitante e abusivo com bebidas alcoólicas'],
    symptomKeywords: ['dor', 'febre', 'dor leve', 'gripe', 'resfriado', 'dengue', 'gestante dor', 'dor dente', 'febre infantil'],
    pregnancyCategory: 'B',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-003',
    name: 'Ibuprofeno',
    activeSubstance: 'Ibuprofeno',
    tradeNames: ['Advil', 'Alivium', 'Ibupril', 'Spidufen', 'Motrin'],
    atcCode: 'ATC_M01AE01',
    pharmaceuticalClass: 'Anti-inflamatório Não Esteroidal (AINE) Derivado do Ácido Propiônico',
    therapeuticClass: 'Anti-inflamatórios e Antirreumáticos',
    pharmaceuticalForms: ['Cápsula Líquida 400mg', 'Comprimido 600mg', 'Suspensão Gotas 50mg/ml', 'Suspensão Gotas 100mg/ml'],
    usualDosages: ['200mg', '400mg', '600mg', '100mg/ml'],
    defaultPosology: '1 comprimido de 400mg a 600mg de 8/8h após as refeições (por até 5 dias)',
    indications: ['Processos inflamatórios agudos', 'Dor muscular e articular', 'Dismenorreia primária (cólica menstrual)', 'Odontalgia'],
    contraindications: ['Úlcera péptica ativa', 'Insuficiência renal ou cardíaca grave', 'Hipertensão descompensada', 'Uso concomitante com Varfarina/Anticoagulantes'],
    symptomKeywords: ['inflamacao', 'dor muscular', 'colica menstrual', 'dor dente', 'garganta inflamada', 'lombalgia', 'dor nas costas', 'artrite', 'torcicolo'],
    pregnancyCategory: 'C (D no 3º trimestre)',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-004',
    name: 'Cetoprofeno',
    activeSubstance: 'Cetoprofeno',
    tradeNames: ['Profenid', 'Bi-Profenid', 'Artrosil', 'Flamador'],
    atcCode: 'ATC_M01AE03',
    pharmaceuticalClass: 'Anti-inflamatório Não Esteroidal (AINE)',
    therapeuticClass: 'Anti-inflamatórios e Antirreumáticos',
    pharmaceuticalForms: ['Comprimido 100mg', 'Comprimido 150mg Bi-Profenid', 'Cápsula 50mg', 'Gel Tópico 2.5%'],
    usualDosages: ['50mg', '100mg', '150mg'],
    defaultPosology: '1 comprimido de 150mg 1 vez ao dia (ou 100mg de 12/12h) após refeição',
    indications: ['Inflamações musculoesqueléticas intensas', 'Tendinites', 'Bursites', 'Lombociatalgia'],
    contraindications: ['Histórico de hemorragia digestiva', 'Asma induzida por AINEs', 'Insuficiência renal grave'],
    symptomKeywords: ['dor forte costas', 'tendinite', 'bursite', 'nervo ciatico', 'inflamacao forte', 'dor no joelho'],
    pregnancyCategory: 'D',
    prescriptionType: 'Sob Prescrição'
  },
  {
    id: 'MED-CAN-005',
    name: 'Dipirona + Orfenadrina + Cafeína',
    activeSubstance: 'Dipirona Monoidratada + Citrato de Orfenadrina + Cafeína Anidra',
    tradeNames: ['Dorflex', 'Doricin', 'Nevralgex', 'Miorrelax', 'Sedalex'],
    atcCode: 'ATC_M03BC51',
    pharmaceuticalClass: 'Analgésico Combinado com Relaxante Muscular de Ação Central',
    therapeuticClass: 'Relaxantes Musculares e Analgésicos',
    pharmaceuticalForms: ['Comprimido', 'Solução Oral Gotas'],
    usualDosages: ['Comprimido padrão', 'Gotas'],
    defaultPosology: '1 a 2 comprimidos de 8/8h ou 6/6h conforme a dor muscular (máx 6 comp/dia)',
    indications: ['Contratura muscular dolorosa', 'Torcicolo', 'Cefaleia tensional associada a tensão cervical'],
    contraindications: ['Glaucoma de ângulo estreito', 'Miastenia gravis', 'Alergia a dipirona'],
    symptomKeywords: ['dor muscular', 'torcicolo', 'musculo travado', 'pescoco travado', 'dorflex', 'tensao muscular', 'contratura'],
    pregnancyCategory: 'C',
    prescriptionType: 'MIP'
  },

  // ─── CARDIOVASCULARES & METABÓLICOS ───────────────────────────────────────
  {
    id: 'MED-CAN-006',
    name: 'Sildenafila',
    activeSubstance: 'Citrato de Sildenafila',
    tradeNames: ['Viagra', 'Pramil', 'Revatio', 'Soluna'],
    atcCode: 'ATC_G04BE03',
    pharmaceuticalClass: 'Inibidor Seletivo da Fosfodiesterase Tipo 5 (PDE-5)',
    therapeuticClass: 'Vasodilatadores e Agentes para Disfunção Erétil',
    pharmaceuticalForms: ['Comprimido Revestido 25mg', 'Comprimido Revestido 50mg', 'Comprimido Revestido 100mg'],
    usualDosages: ['25mg', '50mg', '100mg'],
    defaultPosology: '50mg via oral aproximadamente 1 hora antes da atividade sexual (máx 1 vez ao dia)',
    indications: ['Disfunção erétil', 'Hipertensão Arterial Pulmonar (Revatio)'],
    contraindications: ['CONTRAINDICAÇÃO ABSOLUTA: Uso concomitante com Nitratos (Monocordil, Sustrate, Nitroglicerina)', 'Angina instável', 'Insuficiência cardíaca grave'],
    symptomKeywords: ['disfuncao eretil', 'impotencia', 'viagra', 'vasodilatador'],
    pregnancyCategory: 'B',
    prescriptionType: 'Sob Prescrição'
  },
  {
    id: 'MED-CAN-007',
    name: 'Isossorbida (Mononitrato / Dinitrato)',
    activeSubstance: 'Mononitrato de Isossorbida / Dinitrato de Isossorbida',
    tradeNames: ['Monocordil', 'Sustrate', 'Isocord', 'Coronur'],
    atcCode: 'ATC_C01DA14',
    pharmaceuticalClass: 'Nitrato Vasodilatador Coronariano / Doador de Óxido Nítrico',
    therapeuticClass: 'Vasodilatadores Cardíacos e Antianginosos',
    pharmaceuticalForms: ['Comprimido 20mg', 'Comprimido 40mg', 'Comprimido Sublingual 5mg (Sustrate)'],
    usualDosages: ['5mg', '20mg', '40mg'],
    defaultPosology: '1 comprimido de 20mg a 40mg de 12/12h (com intervalo livre de nitrato de 12h)',
    indications: ['Prevenção e tratamento da Angina Pectoris (Dor no Peito Coronariana)', 'Insuficiência cardíaca congestiva crônica associada'],
    contraindications: ['CONTRAINDICAÇÃO ABSOLUTA com Inibidores de PDE-5 (Sildenafila, Tadalafila)', 'Hipotensão arterial grave', 'Choque cardiogênico'],
    symptomKeywords: ['dor no peito', 'angina', 'coronaria', 'monocordil', 'sustrate', 'infarto prevencao'],
    pregnancyCategory: 'C',
    prescriptionType: 'Sob Prescrição'
  },
  {
    id: 'MED-CAN-008',
    name: 'Losartana Potássica',
    activeSubstance: 'Losartana Potássica',
    tradeNames: ['Aradois', 'Cozaar', 'Losapres', 'Corus'],
    atcCode: 'ATC_C09CA01',
    pharmaceuticalClass: 'Bloqueador dos Receptores de Angiotensina II (BRA)',
    therapeuticClass: 'Anti-hipertensivos',
    pharmaceuticalForms: ['Comprimido Revestido 50mg', 'Comprimido Revestido 100mg'],
    usualDosages: ['50mg', '100mg'],
    defaultPosology: '50mg a 100mg 1 vez ao dia (pela manhã)',
    indications: ['Hipertensão Arterial Sistêmica', 'Proteção renal em nefropatia diabética tipo 2'],
    contraindications: ['Gravidez (2º e 3º trimestres)', 'Uso concomitante com alisquireno em diabéticos'],
    symptomKeywords: ['pressao alta', 'hipertensao', 'remedio de pressao', 'aradois', 'losartana'],
    pregnancyCategory: 'D',
    prescriptionType: 'Sob Prescrição'
  },
  {
    id: 'MED-CAN-009',
    name: 'Varfarina Sódica',
    activeSubstance: 'Varfarina Sódica',
    tradeNames: ['Marevan', 'Coumadin', 'Varfine'],
    atcCode: 'ATC_B01AA03',
    pharmaceuticalClass: 'Anticoagulante Oral Antagonista da Vitamina K',
    therapeuticClass: 'Antitrombóticos e Anticoagulantes',
    pharmaceuticalForms: ['Comprimido 5mg', 'Comprimido 2.5mg'],
    usualDosages: ['2.5mg', '5mg'],
    defaultPosology: 'Dose individualizada ajustada por monitoramento laboratorial de INR (alvo 2.0 a 3.0)',
    indications: ['Prevenção de tromboembolismo venoso (TVP)', 'Embolia pulmonar', 'Prevenção de AVC em Fibrilação Atrial e próteses valvares cardíacas'],
    contraindications: ['Hemorragia ativa grave', 'Uso concomitante com AINEs e salicilatos sem proteção', 'Gravidez'],
    symptomKeywords: ['anticoagulante', 'trombose', 'marevan', 'afinar o sangue', 'fibrilacao atrial', 'tvp'],
    pregnancyCategory: 'X (Contraindicado absoluto na gravidez)',
    prescriptionType: 'Sob Prescrição'
  },
  {
    id: 'MED-CAN-010',
    name: 'Sinvastatina',
    activeSubstance: 'Sinvastatina',
    tradeNames: ['Zocor', 'Sinvasmax', 'Lipitotal', 'Sinvalip'],
    atcCode: 'ATC_C10AA01',
    pharmaceuticalClass: 'Inibidor da HMG-CoA Redutase (Estatina)',
    therapeuticClass: 'Hipolipemiantes e Redutores de Colesterol',
    pharmaceuticalForms: ['Comprimido Revestido 10mg', 'Comprimido Revestido 20mg', 'Comprimido Revestido 40mg'],
    usualDosages: ['10mg', '20mg', '40mg', '80mg'],
    defaultPosology: '20mg a 40mg via oral 1 vez ao dia à noite',
    indications: ['Hipercolesterolemia primária', 'Prevenção secundária de eventos cardiovasculares ateroscleróticos'],
    contraindications: ['Hepatopatia ativa', 'Gravidez e lactação', 'Uso concomitante com inibidores potentes do CYP3A4 (Claritromicina, Fluconazol)'],
    symptomKeywords: ['colesterol alto', 'colesterol', 'triglicerideos', 'gordura no sangue', 'estatina', 'zocor'],
    pregnancyCategory: 'X',
    prescriptionType: 'Sob Prescrição'
  },

  // ─── GASTROINTESTINAIS ───────────────────────────────────────────────────
  {
    id: 'MED-CAN-011',
    name: 'Omeprazol',
    activeSubstance: 'Omeprazol Magnésico',
    tradeNames: ['Losec', 'Peprazol', 'Gastrium', 'Victrix', 'Omeprasec'],
    atcCode: 'ATC_A02BC01',
    pharmaceuticalClass: 'Inibidor da Bomba de Prótons H+/K+ ATPase (IBP)',
    therapeuticClass: 'Antiácidos e Protetores Gástricos',
    pharmaceuticalForms: ['Cápsula 20mg', 'Cápsula 40mg', 'Frasco-Ampola Injetável 40mg'],
    usualDosages: ['20mg', '40mg'],
    defaultPosology: '20mg a 40mg pela manhã em jejum, 30 minutos antes do café da manhã',
    indications: ['Doença do Refluxo Gastroesofágico (DRGE)', 'Úlcera gástrica e duodenal', 'Erradicação de H. pylori', 'Proteção gástrica em uso de AINEs'],
    contraindications: ['Hipersensibilidade a IBPs', 'Atenção ao uso concomitante com Clopidogrel (redução da ativação)'],
    symptomKeywords: ['azia', 'queimacao', 'refluxo', 'dor no estomago', 'gastrite', 'protetor gastrico', 'empachamento'],
    pregnancyCategory: 'C',
    prescriptionType: 'MIP / Sob Prescrição'
  },
  {
    id: 'MED-CAN-012',
    name: 'Hidróxido de Alumínio + Hidróxido de Magnésio + Simeticona',
    activeSubstance: 'Hidróxido de Alumínio + Hidróxido de Magnésio + Simeticona',
    tradeNames: ['Mylanta Plus', 'Gastrobisa', 'Alumag', 'Gelmax'],
    atcCode: 'ATC_A02AF02',
    pharmaceuticalClass: 'Antiácido Neutralizante Combinado com Antiflatulento',
    therapeuticClass: 'Antiácidos e Antiflatulentos',
    pharmaceuticalForms: ['Suspensão Oral Frasco 240ml', 'Comprimidos Mastigáveis'],
    usualDosages: ['10ml a 20ml', '1 a 2 comprimidos'],
    defaultPosology: '10ml a 20ml (ou 1-2 comp mastigáveis) 1 hora após as refeições e ao deitar',
    indications: ['Alívio imediato de hiperacidez gástrica', 'Pirose / Azia aguda', 'Sensação de estômago pesado e gases'],
    contraindications: ['Insuficiência renal grave', 'Espaçar 2 horas da administração de antibióticos e outros fármacos'],
    symptomKeywords: ['azia rapida', 'queimacao agora', 'estomago pesado', 'gases', 'refluxo rapido', 'antiacido'],
    pregnancyCategory: 'B',
    prescriptionType: 'MIP'
  },
  {
    id: 'MED-CAN-013',
    name: 'Sais para Reidratação Oral',
    activeSubstance: 'Cloreto de Sódio + Citrato de Potássio + Citrato de Sódio + Glicose',
    tradeNames: ['Rehidroid', 'Hidrafix', 'Pedialyte', 'Floralyte'],
    atcCode: 'ATC_A07CA',
    pharmaceuticalClass: 'Solução Eletrolítica de Reidratação Oral (Fórmula Padrão Ouro OMS)',
    therapeuticClass: 'Reidratantes e Repositores Eletrolíticos',
    pharmaceuticalForms: ['Envelope / Sachê Pó para Reconstituição em 1 Litro', 'Solução Pronta 500ml'],
    usualDosages: ['Sachê 27.9g / 1000ml'],
    defaultPosology: 'Dissolver 1 sachê em 1 litro de água filtrada ou fervida; ingerir pequenos goles após cada evacuação líquida',
    indications: ['Prevenção e tratamento da desidratação em episódios de diarreia aguda e vômitos'],
    contraindications: ['Íleo paralítico', 'Vômitos incoercíveis com incapacidade de deglutição oral'],
    symptomKeywords: ['diarreia', 'desidratacao', 'vomito', 'soro caseiro', 'reidratacao', 'fraqueza desidratado', 'gastroenterite'],
    pregnancyCategory: 'A',
    prescriptionType: 'MIP'
  },

  // ─── ANTIMICROBIANOS & RESPIRATÓRIOS ─────────────────────────────────────
  {
    id: 'MED-CAN-014',
    name: 'Amoxicilina',
    activeSubstance: 'Amoxicilina Tri-hidratada',
    tradeNames: ['Amoxil', 'Novocilin', 'Velamox', 'Clavulin (com Clavulanato)'],
    atcCode: 'ATC_J01CA04',
    pharmaceuticalClass: 'Antibacteriano Beta-lactâmico / Aminopenicilina',
    therapeuticClass: 'Antimicrobianos Sistêmicos (RDC 20/2011)',
    pharmaceuticalForms: ['Cápsula 500mg', 'Comprimido 875mg', 'Suspensão Oral 250mg/5ml', 'Suspensão Oral 500mg/5ml'],
    usualDosages: ['500mg', '875mg', '250mg/5ml'],
    defaultPosology: '500mg de 8/8h ou 875mg de 12/12h por 7 a 10 dias consecutivos',
    indications: ['Infecções bacterianas de vias aéreas superiores (Sinusite, Amigdalite, Otite)', 'Infecções respiratórias baixas', 'Infecções urinárias'],
    contraindications: ['Hipersensibilidade grave conhecida a penicilinas e beta-lactâmicos'],
    symptomKeywords: ['infeccao', 'garganta com pus', 'sinusite bacteriana', 'otite', 'antibiotico', 'amoxil'],
    pregnancyCategory: 'B',
    prescriptionType: 'Controlado (RDC 20/2011)'
  },
  {
    id: 'MED-CAN-015',
    name: 'Clonazepam',
    activeSubstance: 'Clonazepam',
    tradeNames: ['Rivotril', 'Navotrax', 'Clopam'],
    atcCode: 'ATC_N03AE01',
    pharmaceuticalClass: 'Benzodiazepínico Depressor do SNC / Agonista GABA-A',
    therapeuticClass: 'Ansiolíticos e Anticonvulsivantes (Portaria 344/98 - Lista B1)',
    pharmaceuticalForms: ['Comprimido 0.5mg', 'Comprimido 2.0mg', 'Comprimido Sublingual 0.25mg', 'Solução Oral Gotas 2.5mg/ml'],
    usualDosages: ['0.25mg', '0.5mg', '2.0mg', '2.5mg/ml'],
    defaultPosology: '0.5mg a 2.0mg à noite antes de dormir conforme prescrição médica',
    indications: ['Transtornos de ansiedade e pânico', 'Insônia refratária transitória', 'Crises epilépticas'],
    contraindications: ['Miastenia gravis', 'Insuficiência respiratória grave', 'Apneia do sono', 'Uso concomitante com álcool ou opioides'],
    symptomKeywords: ['ansiedade', 'panico', 'calmante', 'insonia', 'rivotril', 'crise de ansiedade', 'remedio tarja preta'],
    pregnancyCategory: 'D',
    prescriptionType: 'Controlado B1 (Portaria 344/98)'
  }
];
